name: school
description: ICS International School

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.2.0+15

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  image_picker: ^0.8.0+1
  easy_localization: ^3.0.0
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  get: ^4.3.6
  flutter_spinkit: ^5.0.0
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  dio: ^4.0.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.9
  firebase_core: ^2.14.0
  # firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.3
  flutter_local_notifications: ^8.1.1
  youtube_player_flutter: ^8.1.2
  sizer: ^2.0.13
  flutter_pdfview: ^1.2.1
  multi_image_picker2: ^5.0.2
  photo_view: ^0.14.0
  image_gallery_saver: ^1.7.1
  permission_handler: ^10.2.0
  flutter_easyloading: ^3.0.0
  get_storage: ^2.0.3
  device_info: ^2.0.3
  webview_flutter: ^2.0.10
  flutter_image_compress: ^1.0.0-nullsafety
  font_awesome_flutter: ^9.2.0
  badges: ^3.1.1
  flutter_launcher_icons: ^0.9.2
  fl_chart: ^0.63.0
  sliding_up_panel: ^2.0.0+1
  path_provider: ^2.0.11
  keyboard_actions: ^4.1.0
  flutter_html: ^3.0.0-alpha.6
  flutter_heatmap_calendar: ^1.0.5
  qr_flutter: ^4.0.0
  auto_size_text: ^3.0.0
  file_picker: ^5.2.5
  open_document: ^1.0.5
  sticky_headers: ^0.3.0+2
  scrollable_positioned_list: ^0.3.5
  animated_icon: ^0.0.4
  sliver_header_delegate: ^0.0.5
  table_calendar: ^3.0.9
  gallery_saver: ^2.3.2
  geolocator: ^9.0.2
  pinch_zoom: ^1.0.0

  


flutter_icons:
  android: true
  image_path: "assets/icons/login_icon/logo_with_radius.png"
  adaptive_icon_background: "assets/icons/login_icon/adaptive_icon_background.png"
  adaptive_icon_foreground: "assets/icons/login_icon/adaptive_icon_foreground.png"
dependency_overrides:
  test_api: 0.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/icons/home_screen_icon/
    - assets/icons/contact_us_icon/
    - assets/icons/about_us_icon/
    - assets/icons/profile_screen_icon/
    - assets/icons/login_icon/
    - assets/icons/home_screen_icon_one_color/
    - assets/icons/canteen/
    - .env